version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: workbox-build
    versions:
    - 6.0.2
    - 6.1.0
  - dependency-name: workbox-window
    versions:
    - 6.0.2
    - 6.1.0
  - dependency-name: vue-disqus
    versions:
    - 4.0.1
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: ini
    versions:
    - 1.3.8
